camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
  lock-duration: 1000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
  basic-auth:
    username: demo    #put here camundaEngine username
    password: demo    #put here camundaEngine password
  subscriptions:
    my-hml-form-test1-topic:
      variable-names: yourName # only fetch these two variables
      process-definition-key: my-html-form-test-bpmn1

logging.level.org.camunda.bpm.client: DEBUG # increase the log level of the application